### ISSUE TITLE
your face here avatar

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/who#11]
What do people think of having a "your face here" avatar...?
e.g:
![your-face-here-square](https://cloud.githubusercontent.com/assets/194400/9919939/f88d21ca-5cc7-11e5-983f-c6cbe46ed683.jpeg)

**Comment by iteles** [comment]
I think it's great but this isn't a particularly nice one. 

I think 'This could be you!' might be better wording too. But this will be a good holding place until there's time to 'beautify' it.

**Comment by nelsonic** [comment]
@iteles Please find/make a better one.

**Comment by iteles** [comment]
I saw that coming a mile away :see_no_evil:
